### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [vyasriday/watch-next#1]
Hi...
I'm Chimzy, Came across your cool project and as a Logo/Icon Designer who really loves to contribute to awesome open source projects, I want to utilize my logo design skills to help create a unique Logo/Icon for your project, this helps to give the project its own identity.

Working on some idea concepts at the moment... would share the concept here once I am done, so you can give me your feedback, or possible changes or tweaks you might want to suit your needs.

I will appreciate your response...

Regards!

**Comment by vyasriday** [comment]
Sure, I appreciate that. Let me know once you are done with the concepts you are working on.

**Comment by chimzycash** [comment]
I appreciate your quick response... I am basically doing it for free as my Love for Contributing to Open Source Projects :)...

Would share the concept here once i'm done for your feedback.

**Comment by chimzycash** [comment]
Hi @vyasriday ... Here is my idea concept for your logo design... You can give your feedback and also your preferred color of choice...

![LOGO DESIGN_WATCHNEXT_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/59196170-dad7d580-8b85-11e9-8b97-3182783730ba.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/59196171-db706c00-8b85-11e9-8050-f897ae3b03af.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/59196173-db706c00-8b85-11e9-8b2b-158a0b50692f.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/59196175-dc090280-8b85-11e9-9fd9-43ac2886da3e.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/59196176-dca19900-8b85-11e9-979a-0f63130f5139.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_6](https://user-images.githubusercontent.com/37814297/59196179-ddd2c600-8b85-11e9-9595-ac56d61df597.jpg)
![LOGO DESIGN_WATCHNEXT_idea concept_NEW](https://user-images.githubusercontent.com/37814297/59196180-de6b5c80-8b85-11e9-9c84-e945ff46c387.jpg)

**Comment by vyasriday** [comment]
I will go with the first one. That looks good to me. And for the color I think the app is mostly dark themed so red will be good.

**Comment by chimzycash** [comment]
I appreciate your quick response... Glad that you liked the design...
The different arrangements are basically how the logo can be used and still maintain its visual identity.

Would prepare all the files including the vector files for your use

**Comment by chimzycash** [comment]
Here is the logo on a dark background, also included a black and red icon...

![LOGO DESIGN_WATCHNEXT_BACKGROUND_7](https://user-images.githubusercontent.com/37814297/59287927-93774500-8c6a-11e9-9d38-e1bc536ce3bd.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_8](https://user-images.githubusercontent.com/37814297/59287932-93774500-8c6a-11e9-8676-9a6901b6a7dc.jpg)
![LOGO DESIGN_WATCHNEXT_BACKGROUND_9](https://user-images.githubusercontent.com/37814297/59287935-940fdb80-8c6a-11e9-9c83-555a877c3607.jpg)

**Comment by vyasriday** [comment]
Cool

**Comment by chimzycash** [comment]
Glad that you liked it...  I Created a pull request with the logo files.

**Comment by vyasriday** [comment]
Yeah I saw that. I will merge it once I work on it. I'm working on something else right now.

**Comment by chimzycash** [comment]
Okay... Feel free to hit me up if you need any more logo files
Also... you can hit me up if you need any help for any open source project... would be glad to help contribute...

**Comment by vyasriday** [comment]
Sure.  Working on a small project. Will let you know once it's over.

**Comment by chimzycash** [comment]
Here is the Google Drive link containing the files also with the vector files for your use.
